/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PesoRouteImport } from './routes/peso'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NutricaoRouteImport } from './routes/nutricao'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreinoIndexRouteImport } from './routes/treino.index'
import { Route as TreinoAtivoRouteImport } from './routes/treino.ativo'

const PesoRoute = PesoRouteImport.update({
  id: '/peso',
  path: '/peso',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NutricaoRoute = NutricaoRouteImport.update({
  id: '/nutricao',
  path: '/nutricao',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoIndexRoute = TreinoIndexRouteImport.update({
  id: '/treino/',
  path: '/treino/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoAtivoRoute = TreinoAtivoRouteImport.update({
  id: '/treino/ativo',
  path: '/treino/ativo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/nutricao': typeof NutricaoRoute
  '/perfil': typeof PerfilRoute
  '/peso': typeof PesoRoute
  '/treino/ativo': typeof TreinoAtivoRoute
  '/treino/': typeof TreinoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/nutricao': typeof NutricaoRoute
  '/perfil': typeof PerfilRoute
  '/peso': typeof PesoRoute
  '/treino/ativo': typeof TreinoAtivoRoute
  '/treino': typeof TreinoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/nutricao': typeof NutricaoRoute
  '/perfil': typeof PerfilRoute
  '/peso': typeof PesoRoute
  '/treino/ativo': typeof TreinoAtivoRoute
  '/treino/': typeof TreinoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/nutricao'
    | '/perfil'
    | '/peso'
    | '/treino/ativo'
    | '/treino/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/nutricao'
    | '/perfil'
    | '/peso'
    | '/treino/ativo'
    | '/treino'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/nutricao'
    | '/perfil'
    | '/peso'
    | '/treino/ativo'
    | '/treino/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  NutricaoRoute: typeof NutricaoRoute
  PerfilRoute: typeof PerfilRoute
  PesoRoute: typeof PesoRoute
  TreinoAtivoRoute: typeof TreinoAtivoRoute
  TreinoIndexRoute: typeof TreinoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/peso': {
      id: '/peso'
      path: '/peso'
      fullPath: '/peso'
      preLoaderRoute: typeof PesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutricao': {
      id: '/nutricao'
      path: '/nutricao'
      fullPath: '/nutricao'
      preLoaderRoute: typeof NutricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino/': {
      id: '/treino/'
      path: '/treino'
      fullPath: '/treino/'
      preLoaderRoute: typeof TreinoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino/ativo': {
      id: '/treino/ativo'
      path: '/treino/ativo'
      fullPath: '/treino/ativo'
      preLoaderRoute: typeof TreinoAtivoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  NutricaoRoute: NutricaoRoute,
  PerfilRoute: PerfilRoute,
  PesoRoute: PesoRoute,
  TreinoAtivoRoute: TreinoAtivoRoute,
  TreinoIndexRoute: TreinoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
